title: <p align="center"> Tuan Nguyen </p>

logo: "/images/photo1.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/tuan-nguyen-b150a61a0/">LinkedIn</a> |
  <a href="https://github.com/tuanspjain">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing my Bachelor of Data Science degree at S P Jain School of Global Management, Sydney.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal

